# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # catch SNAPSHOT breaking changes, check before THU OSLC calls and on Sat
    - cron: "30 4 * * 4,6" 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk: ['8', '11']
        distribution: ['temurin']
        experimental: [false]
        # include:
        #   - jdk: '23'
        #     distribution: 'zulu'
        #     experimental: true
        #   - jdk: '24-ea'
        #     distribution: 'zulu'
        #     experimental: true
    continue-on-error: ${{ matrix.experimental }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.jdk }}
        distribution: ${{ matrix.distribution }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
